services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\DoctrineIpBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'

  doctrine-ip.property-accessor:
    class: Symfony\Component\PropertyAccess\PropertyAccessor
    factory: [ 'Symfony\Component\PropertyAccess\PropertyAccess', 'createPropertyAccessor' ]
